name: Base CI
on:
  push:

jobs:
  ci:
    runs-on: ubuntu-latest
    env:
      API_KEY: ${{ secrets.API_KEY }}
      AUTH_DOMAIN: ${{ secrets.AUTH_DOMAIN }}
      APP_ID: ${{ secrets.APP_ID }}
      PROJECT_ID: ${{ secrets.PROJECT_ID }}
      STORAGE_BUCKET: ${{ secrets.STORAGE_BUCKET }}
      MESSAGING_SENDER_ID: ${{ secrets.MESSAGING_SENDER_ID }}
      RAPID_YAHOO_API_KEY: ${{ secrets.RAPID_YAHOO_API_KEY }}

    steps:
      - uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '20'

      - name: Install dependencies
        run: npm ci

      - name: Lint
        run: npm run lint

      - name: Test
        run: npm test

      - name: Build
        run: npm run build

      - name: Upload build artifacts
        uses: actions/upload-artifact@v2
        with:
          name: dist
          path: dist
